# Large Geospatial data handling in Julia
### BiDS BIG DATA FROM SPACE 2023
- November 6, 2023
- 2:00 PM - 5:30 PM
- Vienna, Austria

> Lazaro Alonso  & Felix Cremer
> - <font color = teal> **Max Planck Institute for Biogeochemistry** </font>
> - Model-Data Integration Group 
> - <font color = orange> **ELLIS Unit Jena** </font>

>  lalonso@bgc-jena.mpg.de

Find me also on social media:

<img src="X_logo_2023.svg" alt="X" width="16"/>
@LazarusAlon

<img src="github-mark-white.svg" width=20/> lazarusA 


#### References:
Get Julia:
> https://julialang.org/downloads/

Start learning:

- https://docs.julialang.org
- https://docs.julialang.org/en/v1/manual/performance-tips/

> https://juliadatascience.io
    > by Jose Storopoli, Rik Huijzer and Lazaro Alonso

### Agenda

|   Time   |           Topic           |
|----------|---------------------------|
|  14:00   | <font color = orangered> **Introduction to Julia**</font>    |
|  14:30   | <font color = orangered> **Julia Geo Ecosystem**</font>       |
|  15:00   | Raster Data Loading       |
|  15:30   | Coffee Break              |
|  15:50   | Raster Data Analysis      |
|  16:10   | Hands-On Challenge <font color = dodgerblue> **_Plotting Data Cubes_**</font>       |


## Introduction to Julia
Again, if you don't have it, please install Julia:
> https://julialang.org/downloads/

and the editor I will be using is vscode:

> https://code.visualstudio.com

## What is and why Julia?

* Published around 2012 initially developped at MIT
* Just in Time compiled
* Optionally typed
* Gives you the best of C, Matlab and Python
* Function oriented not object oriented
* solves the two language problem

### Julia’s Syntax in a nutshell
- **Variables**
- struct
- Boolean Operators and Numeric comparisons
- Functions
- Multiple Dispatch
- Keyword arguments
- Anonymous Functions
- Conditionals

#### Project Management

```shell
] activate .
] add package
] dev --local package
; # get you into shell mode /terminal
julia> ?
help?>
```

#### variables

In [1]:
name = "Julia"
age = 12 # years

12

In [2]:
name

"Julia"

In [3]:
# operations on variables, addition, multiplication
10*age

120

In [4]:
10 + age

22

Q. What type of variables are those? 
> Use `typeof` and find out. 

In [6]:
typeof(age)

Int64

In [7]:
typeof(name)

String

#### struct

Having variables around without any sort of hierarchy or relationships is not ideal. In Julia, we can define that kind of structured data with a struct (also known as a composite type).

_Basic, basic, of course the following is not the whole story, but is enough to get us started_

- https://docs.julialang.org/en/v1/manual/performance-tips/#Type-declarations

In [8]:
struct Language
    name::String
    title::String
    year_of_birth::Int64
    fast::Bool
end

In [9]:
fieldnames(Language)

(:name, :title, :year_of_birth, :fast)

Q. How to use them?
> Instantiate as in:

In [10]:
julia = Language("Julia", "Rapidus", 2012, true)

Language("Julia", "Rapidus", 2012, true)

In [11]:
python = Language("Python", "Letargicus", 1991, false)

Language("Python", "Letargicus", 1991, false)

#### mutable struct

<font color=red>We can’t change their values once they are instantiated.</font>
But, what if I want to update some of those variables, then we use a `mutable struct`.

In [12]:
mutable struct MutableLanguage
    name::String
    title::String
    year_of_birth::Int64
    fast::Bool
end

In [13]:
julia_mutable = MutableLanguage("Julia", "Rapidus", 2012, true)

MutableLanguage("Julia", "Rapidus", 2012, true)

In [14]:
julia_mutable.title = "Python Obliteratus"

"Python Obliteratus"

In [15]:
julia_mutable

MutableLanguage("Julia", "Python Obliteratus", 2012, true)

####  **Boolean Operators and Numeric comparisons**

In [16]:
!true

false

In [17]:
(false && true) || (!false)

true

In [18]:
(6 isa Int64) && (6 isa Real)

true

In [19]:
# equality
1 == 1

true

In [20]:
# less than
1<2

true

In [21]:
# less than or equal to
3.14 <= 3.14

true

In [22]:
# mix with boolean 
(1 != 10) || (3.14 <= 2.71)

true

#### Functions & Multiple Dispatch

In [23]:
f_name(arg1, arg2) = arg1 + arg2

f_name (generic function with 1 method)

In [24]:
function fuction_name(arg1, arg2)
    return arg1 + arg2
end

fuction_name (generic function with 1 method)

In [25]:
f(x,y) = x + y

f (generic function with 1 method)

In [26]:
f(1,2)

3

In [27]:
f(2.0, 1.0)

3.0

<font color = red > type declarations </font> Multiple dispatch

- https://docs.julialang.org/en/v1/manual/methods/#Defining-Methods

In [28]:
function round_number(x::Float64)
    return round(x)
end

round_number (generic function with 1 method)

In [29]:
function round_number(x::Int64)
    return x
end

round_number (generic function with 2 methods)

In [49]:
round_number(2.1)

2.0

In [52]:
# broadcasting
round_number.(10*rand(10))

10-element Vector{Float64}:
 6.0
 7.0
 0.0
 7.0
 9.0
 2.0
 5.0
 6.0
 6.0
 5.0

**multiple return values**

In [30]:
function add_multiply(x, y)
    addition = x + y
    multiplication = x * y
    return addition, multiplication
end

add_multiply (generic function with 1 method)

In [31]:
add_multiply(1, 2)

(3, 2)

In [32]:
out = add_multiply(1, 2)

(3, 2)

In [33]:
first(out)

3

In [34]:
last(out)

2

#### Keyword arguments

In [36]:
function logarithm(x::Real; base::Real=2.7182818284590)
    return log(base, x)
end

logarithm (generic function with 1 method)

In [37]:
logarithm(10)

2.3025850929940845

In [38]:
logarithm(10; base=2)

3.3219280948873626

#### Anonymous Functions

Often we don’t care about the name of the function and want to quickly make one.

In [40]:
map(x -> 2.7182818284590^x, logarithm(2))

2.0

#### Conditionals

Let's compare two numbers, `a` and `b`.

In [41]:
function compare(a, b)
    if a < b
        "a is less than b"
    elseif a > b
        "a is greater than b"
    else
        "a is equal to b"
    end
end

compare (generic function with 1 method)

In [42]:
compare(3.14, 3.14)

"a is equal to b"

A pattern that I use a lot is the following:

In [43]:
function compare_ternary(a, b)
    a < b ? "a is less than b" : a > b ? "a is greater than b" : "a is equal to b"
end

compare_ternary (generic function with 1 method)

In [44]:
compare_ternary(3.14, 3.14)

"a is equal to b"

**The `for` loop ! Use it!**

In [45]:
for i in 1:5
    println(i)
end

1
2
3
4
5


#### Native Data Structures
- **String**
- Tuple
- NamedTuple
- UnitRange
- Array
- Pair
- Dict
- Symbol

In [53]:
str1 = "This is a string"

"This is a string"

In [54]:
typeof(str1)

String

In [55]:
str2 = """
    This is a big multiline string with a nested "quotation".
    As you can see.
    It is still a String to Julia.
    """

"This is a big multiline string with a nested \"quotation\".\nAs you can see.\nIt is still a String to Julia.\n"

In [56]:
typeof(str2)

String

In [57]:
# concatenation
hello = "Hello"
goodbye = "Goodbye"

"Goodbye"

In [58]:
hello*goodbye

"HelloGoodbye"

In [59]:
join([hello, goodbye], " ")

"Hello Goodbye"

In [60]:
# String Interpolation
"$hello $goodbye"

"Hello Goodbye"

In [61]:
function compare_interpolate(a, b)
    a < b ? "$a is less than $b" : a > b ? "$a is greater than $b" : "$a is equal to $b"
end

compare_interpolate (generic function with 1 method)

In [62]:
compare_interpolate(3.14, 3.14)

"3.14 is equal to 3.14"

**Functions to manipulate strings**

In [63]:
julia_string = "Julia is an amazing open source programming language"

"Julia is an amazing open source programming language"

In [64]:
contains(julia_string, "Julia")

true

In [66]:
endswith(julia_string, "Julia")

false

In [67]:
lowercase(julia_string)

"julia is an amazing open source programming language"

In [68]:
uppercase(julia_string)

"JULIA IS AN AMAZING OPEN SOURCE PROGRAMMING LANGUAGE"

In [69]:
titlecase(julia_string)

"Julia Is An Amazing Open Source Programming Language"

In [70]:
lowercasefirst(julia_string)

"julia is an amazing open source programming language"

In [71]:
replace(julia_string, "amazing" => "awesome")

"Julia is an awesome open source programming language"

In [72]:
split(julia_string, " ")

8-element Vector{SubString{String}}:
 "Julia"
 "is"
 "an"
 "amazing"
 "open"
 "source"
 "programming"
 "language"

In [73]:
string(123)

"123"

In [74]:
parse(Int64, "123")

123

In [76]:
# tuple
my_tuple = (1, 3.14, "Julia") # immutable struct

(1, 3.14, "Julia")

In [77]:
add_mul = add_multiply(1, 2)

(3, 2)

In [78]:
typeof(add_mul)

Tuple{Int64, Int64}

Mix anonymous functions and tuples

In [79]:
map((x, y) -> x^y, 2, 3)

8

In [80]:
map((x, y, z) -> x^y + z, 2, 3, 1)

9

In [81]:
# NamedTuple
my_namedtuple = (; i=1, f=3.14, s="Julia")

(i = 1, f = 3.14, s = "Julia")

In [82]:
my_namedtuple.f

3.14

In [83]:
it = 1
ft = 3.14
st = "Julia"

"Julia"

Begin the named tuple construction by specifying first a semicolon ; before the values

In [84]:
my_quick_namedtuple = (; it, ft, st)

(it = 1, ft = 3.14, st = "Julia")

In [85]:
1:10

1:10

In [86]:
typeof(1:10)

UnitRange{Int64}

In [87]:
0.0:0.2:1.0

0.0:0.2:1.0

In [88]:
typeof(0.0:0.2:1.0)

StepRangeLen{Float64, Base.TwicePrecision{Float64}, Base.TwicePrecision{Float64}, Int64}

In [89]:
# array
collect(1:5)

5-element Vector{Int64}:
 1
 2
 3
 4
 5

In [90]:
myarray = [1, 2, 3]

3-element Vector{Int64}:
 1
 2
 3

Let’s start with array types. There are several, but we will focus on the following two

- Vector{T}: one-dimensional array. Alias for Array{T, 1}.
- Matrix{T}: two-dimensional array. Alias for Array{T, 2}.

In [91]:
my_vector = Vector{Float64}(undef, 10)

10-element Vector{Float64}:
 2.890241183e-314
 2.8902411907e-314
 2.248727131e-314
 2.3963341834e-314
 2.396330389e-314
 2.890378968e-314
 2.396330389e-314
 2.396338215e-314
 2.396330737e-314
 2.396338215e-314

In [92]:
my_matrix = Matrix{Float64}(undef, 10, 2)

10×2 Matrix{Float64}:
 2.22795e-314  2.22795e-314
 2.22795e-314  2.22795e-314
 2.22795e-314  2.22795e-314
 2.22795e-314  2.22795e-314
 2.22795e-314  2.22795e-314
 2.22795e-314  2.22795e-314
 2.22795e-314  2.22795e-314
 2.22795e-314  2.22795e-314
 2.22795e-314  2.22795e-314
 2.22795e-314  2.22795e-314

**Common arrays**

In [93]:
zeros(3,3)

3×3 Matrix{Float64}:
 0.0  0.0  0.0
 0.0  0.0  0.0
 0.0  0.0  0.0

In [94]:
ones(Int64, 3,3)

3×3 Matrix{Int64}:
 1  1  1
 1  1  1
 1  1  1

This also works: (array literals)

In [95]:
[[1 2]
 [3 4]]

2×2 Matrix{Int64}:
 1  2
 3  4

In [96]:
Float64[[1 2]
        [3 4]]

2×2 Matrix{Float64}:
 1.0  2.0
 3.0  4.0

In [97]:
# mix and match
[ones(Int, 2, 2) zeros(Int, 2, 2)]

2×4 Matrix{Int64}:
 1  1  0  0
 1  1  0  0

In [98]:
# array comprehension
[x^2 for x in 1:5]

5-element Vector{Int64}:
  1
  4
  9
 16
 25

In [99]:
[x*y for x in 1:5 for y in 1:2]

10-element Vector{Int64}:
  1
  2
  2
  4
  3
  6
  4
  8
  5
 10

In [100]:
[x*y for x in 1:5, y in 1:2]

5×2 Matrix{Int64}:
 1   2
 2   4
 3   6
 4   8
 5  10

In [101]:
# conditional
[x^2 for x in 1:5 if isodd(x)]

3-element Vector{Int64}:
  1
  9
 25

- **Pair**
- **Dict**
- **Symbol**

In [102]:
my_pair = "Julia" => 42

"Julia" => 42

In [103]:
name2number_map = Dict("one" => 1, "two" => 2)

Dict{String, Int64} with 2 entries:
  "two" => 2
  "one" => 1

In [104]:
sym = :some_text

:some_text

**Splat Operator**

In [105]:
add_elements(a, b, c) = a + b + c

add_elements (generic function with 1 method)

In [106]:
my_collection = [1, 2, 3]

3-element Vector{Int64}:
 1
 2
 3

In [107]:
add_elements(my_collection...)

6

In [108]:
add_elements(1:3...)

6

### Plotting? Do we have time ?

In [110]:
using Pkg
Pkg.status()

Status `~/Documents/BiDS23/intro/Project.toml`
  [e9467ef8] GLMakie v0.8.12
  [37e2e46d] LinearAlgebra
  [9a3f8284] Random


In [111]:
Pkg.add("GLMakie")

   Resolving package versions...


  No Changes to `~/Documents/BiDS23/intro/Project.toml`
  No Changes to `~/Documents/BiDS23/intro/Manifest.toml`


In [112]:
using GLMakie
GLMakie.activate!()

In [117]:
x = y = z = -1:0.2:1
vol1 = [ix * iy * iz for ix in x, iy in y, iz in z]
points3d = [Point3f(ix, iy, iz) for ix in x, iy in y, iz in z];
# colormap
alphas = [x^2 for x in range(-1, 1, length = 101)]
cmap_alpha = resample_cmap(:Hiroshige, 101; alpha = alphas)

In [118]:
fig = Figure(resolution = (500, 500))
ax = Axis3(fig[1, 1], perspectiveness = 0.5, azimuth = 7.38,
    elevation = 0.57, aspect = (1, 1, 1))
meshscatter!(ax, vec(points3d); color = vec(vol1), colormap = cmap_alpha)
fig